apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: turkialq/multi-worker
          env:
            - name: REDIS_HOST
              value: redis-srv
            - name: REDIS_PORT
              value: "6379"
