name: Deploy MultiK8s
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get SHA
        id: vars
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Test React Client
        run: |
          docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true cygnetops/react-test npm test

      - name: Set up Google Cloud Authentication
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set up Google Cloud Project
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Google Cloud
        run: gcloud --quiet auth configure-docker

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v0.2.0
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}

      - name: Build Docker Images
        run: |
          docker build -t cygnetops/multi-client-k8s-gh:latest -t cygnetops/multi-client-k8s-gh:${{ steps.vars.outputs.sha }} -f ./client/Dockerfile ./client
          docker build -t cygnetops/multi-server-k8s-pgfix-gh:latest -t cygnetops/multi-server-k8s-pgfix-gh:${{ steps.vars.outputs.sha }} -f ./server/Dockerfile ./server
          docker build -t cygnetops/multi-worker-k8s-gh:latest -t cygnetops/multi-worker-k8s-gh:${{ steps.vars.outputs.sha }} -f ./worker/Dockerfile ./worker

      - name: Push Docker Images
        run: |
          docker push cygnetops/multi-client-k8s-gh:latest
          docker push cygnetops/multi-server-k8s-pgfix-gh:latest
          docker push cygnetops/multi-worker-k8s-gh:latest
          docker push cygnetops/multi-client-k8s-gh:${{ steps.vars.outputs.sha }}
          docker push cygnetops/multi-server-k8s-pgfix-gh:${{ steps.vars.outputs.sha }}
          docker push cygnetops/multi-worker-k8s-gh:${{ steps.vars.outputs.sha }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=cygnetops/multi-server-k8s-pgfix-gh:${{ steps.vars.outputs.sha }}
          kubectl set image deployments/client-deployment client=cygnetops/multi-client-k8s-gh:${{ steps.vars.outputs.sha }}
          kubectl set image deployments/worker-deployment worker=cygnetops/multi-worker-k8s-gh:${{ steps.vars.outputs.sha }}
