name: Deploy MultiK8s

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get SHA
        run: echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ... rest of your steps

      - name: Build Docker Images
        run: |
          docker build -t cygnetops/multi-client-k8s-gh:latest -t cygnetops/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          # ... other docker build commands

      - name: Push Docker Images
        run: |
          docker push cygnetops/multi-client-k8s-gh:latest
          # ... other docker push commands

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=cygnetops/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          # ... other kubectl set image commands
